language: cpp

sudo: required
dist: trusty

cache:
  bundler: true
  directories:
    - $HOME/temp/

install:
    - function timeout() { perl -e 'alarm shift; exec @ARGV' "$@"; }
  
script:
    - timeout 160 scripts/wait_script.sh
