language: cpp

sudo: required
dist: trusty

env:
  - JOB=good
  - JOB=bad

script:
  - |
    ls -l
    cd /var
    ls -l
    cd /
    ls -l
    cd /var
    mkdir pages
    if [ $JOB == "good" ]; then scripts/good_script.sh
    fi
    if [ $JOB == "bad" ]; then scripts/bad_script.sh
    fi

